FROM ubuntu
LABEL maintainer='Java Home CLoud' \
        emplyee_name='Sameed_shoaib'\
        version=1.0.0
RUN apt-get update -y
RUN apt-get install apache2 -y
RUN apt-get install wget -y
RUN apt-get install unzip -y
WORKDIR /tmp
RUN wget https://github.com/javahometech/javahome-app/archive/master.zip
RUN unzip master.zip

  # Move the code from /tmp to apache directory /var/www/html

RUN mv javahome-app-master/* /var/www/html/
EXPOSE 80
CMD ["apachectl","-D","FOREGROUND"] IT will be executed when the container is started)

